services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus-repository
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "5000:5000"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - websites

volumes:
  nexus-data:
    driver: local
networks:
  websites:
    external: true
