version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin@123456"
      MSSQL_PID: "Developer"   # or "Express", "Standard", "Enterprise"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
